### PR TITLE
Fix resolvers typings with `react-hook-form@7.15.0`

### LINKED ISSUE #234: yupResolver raise Types of parameters 'options' and 'options' are incompatible at react-hook-form 7.15.0
Hello.

**Describe the bug**

I updated react-hook-form 7.15.0, yupResolver raise following type error messages.

```
Type '<TFieldValues extends Record<string, any>, TContext>(values: UnpackNestedValue<TFieldValues>, context: TContext | undefined, options: ResolverOptions<TFieldValues>) => Promise<...>' is not assignable to type 'Resolver<FormType, object>'.
  Types of parameters 'options' and 'options' are incompatible.
```

Same code with react-hook-form 7.14.2 works fine(no type error).

versions
- react: 17.0.2
- react-hook-form: 7.15.0
- @hookform/resolvers: 2.8.0
- dayjs: 1.10.6
- yup: 0.32.9
- typescript: 4.3.5

**To Reproduce**

1. Go to https://codesandbox.io/s/sad-wilson-rvpvv?file=/src/App.tsx
2. move mouse cursor to line 22 and hover `resolver`
3. Error message popup.

**Codesandbox link (Required)**

https://codesandbox.io/s/sad-wilson-rvpvv?file=/src/App.tsx:456-464

**Expected behavior**

No type error raised, or I want to know how to avoid type error
(react-hook-form 7.14.2 works fine)

**Screenshots**

スクリーンショット 2021-09-07 22 26 31

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome
- Version 92.0.4515.159（Official Build） （x86_64）

**Additional context**

None

Thank you!

### PR DESCRIPTION
**Pull request by julienfouilhe**
I upgraded to the latest `react-hook-form` and `@hookform/resolvers` versions and all of a sudden all my forms that were using the `yupResolver` were throwing a typescript error while those using the io-ts resolver (I'm progressively migrating to io-ts) didn't.

I checked what could be the source and figured the typings were not infered properly when wrapping the generic function.

Example of something that does not work:

```typescript
const { register } = useForm<Type>({
  resolver: yupResolver(schema),
});
```

Fixes #234

### CODE REVIEW

**Comment by bluebill1049** [comment]
thanks for the contribution 💪

File: superstruct/src/types.ts [hunk 1]
```diff
@@ -8,10 +7,10 @@ import { validate, Struct } from 'superstruct';
 
 type Options = Parameters<typeof validate>[2];
 
-export type Resolver = <T extends Struct<any, any>>(
+export type Resolver = <T extends Struct<any, any>, TFieldValues, TContext>(
   schema: T,
   factoryOtions?: Options,
```
Comment (alb7h) [inline superstruct/src/types.ts:12]:
```suggestion
  factoryOptions?: Options,
```

just because it was slightly bothering me 😄

**Comment by alb7h** [comment]
@bluebill1049 Any idea when this'll get merged?

**Comment by bluebill1049** [comment]
let's wait for @jorisre he is the master mind behind resolver.

**Comment by julienfouilhe** [comment]
@bluebill1049 Any idea when @jorisre will be available to review this? Upgrading to the latest version of react-hook-form is impossible because of this issue.

**Comment by bluebill1049** [comment]
Hey @julienfouilhe I will review it now, and I have also pinged Joris too.

File: class-validator/src/types.ts [hunk 2]
```diff
@@ -7,11 +7,15 @@ import {
 import { ValidatorOptions } from 'class-validator';
 import { ClassConstructor } from 'class-transformer';
 
-export type Resolver = <T extends { [_: string]: any }>(
+export type Resolver = <
+  T extends { [_: string]: any },
+  TFieldValues extends FieldValues,
+  TContext,
```
Comment (bluebill1049) [inline class-validator/src/types.ts:13]: 👍

File: zod/src/zod.ts [hunk 3]
```diff
@@ -64,22 +64,22 @@ export const zodResolver: Resolver =
       options.shouldUseNativeValidation && validateFieldsNatively({}, options);
 
       return {
-        errors: {},
+        errors: {} as FieldErrors<any>,
```
Comment (bluebill1049) [inline zod/src/zod.ts:67]: wondering why have to start casting now.

**Review by bluebill1049 — APPROVED** [review]
LGTM.

**Comment by bluebill1049** [comment]
> Sorry for the delay. I'll look at it tonight

Merci

**Comment by jorisre** [comment]
We loose the return type for the resolvers:
Screenshot 2021-09-16 at 12 30 17

We are getting
```ts
{
    [x: string]: any;
}
```

instead of the values. That why the resolvers types is a bit different

**Comment by julienfouilhe** [comment]
@jorisre What would be the expected signature? I feel like values should always be typed unknown, and we should infer the TFieldValues from the schema, like this: 

```typescript
import { ResolverResult, ResolverOptions, FieldValues } from 'react-hook-form';
import { z } from 'zod';

export type Resolver = <TFieldValues extends FieldValues, TContext>(
  schema: z.Schema<TFieldValues, any>,
  schemaOptions?: Partial<z.ParseParamsNoData>,
  factoryOptions?: { mode?: 'async' | 'sync' },
) => (
  values: unknown,
  context: TContext | undefined,
  options: ResolverOptions<TFieldValues>,
) => Promise<ResolverResult<TFieldValues>>;
```

File: zod/src/zod.ts (hunk 3 above)
Comment (julienfouilhe) [reply zod/src/zod.ts:67]: I don't know exactly but seems like an empty object is not assignable to the DeepMap with the new version of FieldErrors from react-hook-form?

**Review by jorisre — DISMISSED** [review]
Thank you for the contribution @julienfouilhe !

LGTM! I'll make some minor changes in another PR.

Sorry again for the delay.

**Comment by julienfouilhe** [comment]
@jorisre I fixed the tests sorry about that. Thought I had run them.

I had to add unpacking NestedValue support to io-ts

**Review by jorisre — APPROVED** [review]

**Comment by bluebill1049** [comment]
thank you @julienfouilhe & @jorisre ❤️
